url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Step By Step" # the name of your site, e.g. ACME Corp.
desc: "A fullstack developer, love programming and live."


show_excerpts: true
